export const PAGE_CONTENT_HIDE = 'PAGE_CONTENT_HIDE'
export const PAGE_CONTENT_SHOW = 'PAGE_CONTENT_SHOW'
export const PAGE_NUMBER_RESET = 'PAGE_NUMBER_RESET'
export const PAGE_NUMBER_ADD = 'PAGE_NUMBER_ADD'
export const PAGE_NUMBER_SUB = 'PAGE_NUMBER_SUB'
export const PAGE_NUMBER_CHANGE = 'PAGE_NUMBER_CHANGE'
export const PAGE_NUMBER_LAST = 'PAGE_NUMBER_LAST'

